---
- name: install apache
  yum: name=httpd state:present

- name: copy index.html
  template: src=index.html.j2 dest={{apache_docroot}}/index.html
  notify: restart apache

- name: ensure apache is running
  service: name=httpd state=started enabled=yes

