---
- name: install ntp
  yum: name=ntp state=present

- name: configura ntp file
  template: src:ntp.conf.j3 dest=/etc/ntp.conf
  notify: restart ntp

- name: start ntp
  service: name=ntpd state=started